### ISSUE TITLE
Respect semantic versioning

### ISSUE THREAD

**Issue by Silthus** [EntryPointKR/Spigradle#12]
Hi,
first off thanks for the awesome gradle plugin and improvements in version 1.3.0.

However it would be nice if semantic versioning rules are honored and the major version is bumped if there are breaking changes.

If you want I can also help with setting up a fully automated release workflow using [semantic-release](https://github.com/semantic-release/semantic-release) that does the following for you:
- bump the version automatically based on the [conventional commits](https://www.conventionalcommits.org/) format
- creates a changelog from your commit messages
- publishes your gradle plugin to the repository 
- creates a tag and corresponding release in github 
- comments on all issues related to the release letting your users know the version the issue is included in

You can see an example of it here: https://github.com/Silthus/spigot-plugin-template

Thanks!

**Comment by EntryPointKR** [comment]
Good to know. about the versioning, I think must continue to 1.3.1 because 1.3.0 already published. on the next breaking change I'll bump up the major. but if it's okay to publish 2.0.0 instead of 1.3.1, I'll do it.
About semantic-release, it looks nice. I actually had pain in writing changelogs. I'll consider to install it with TeamCity if possible.

**Comment by Silthus** [comment]
Awesome, thank you!

Send me a message on Discord (Silthus#4973) if you have any questions or need some help.

**Comment by EntryPointKR** [comment]
Thanks, @Silthus!

**Comment by EntryPointKR** [comment]
No, rather than continue to 1.x, release 1.4 with restore breaking changes, and continue to 2.0 would be better. I'll release both versions.
