### ISSUE TITLE
1.3.0: @PluginMain does not work on subclasses of JavaPlugin

### ISSUE THREAD

**Issue by Silthus** [EntryPointKR/Spigradle#13]
There is a bug in `1.3.0` where the plugin fails to find the correct main class annotated wit `@PluginMain` if it is not a direct subclass of `JavaPlugin`.

This works:

```java
@kr.entree.spigradle.PluginMain
public class ExamplePlugin extends JavaPlugin {
}
```

This does not work, but worked in the version before `1.3.0`:

```java
@kr.entree.spigradle.PluginMain
public class ExamplePlugin extends BasePlugin {}
```

```java
public class BasePlugin extends JavaPlugin {}
```

**Comment by EntryPointKR** [comment]
Hi Silthus, it should be fixed by 68ea84c. 
Currently 1.3.1-SNAPSHOT is available on the repository https://oss.jfrog.org/artifactory/oss-snapshot-local/. 
This will released soon.

Apply example:

```groovy
buildscript {
    repositories {
        maven { url 'https://oss.jfrog.org/artifactory/oss-snapshot-local/' }
    }

    dependencies {
        classpath 'kr.entree:spigradle:1.3.1-20200626.123538-2'
    }
}

plugins { }

apply plugin: 'kr.entree.spgiradle'
```

If still happen the bug, please reopen the issue. Thanks!

**Comment by EntryPointKR** [comment]
1.3.1 is published, now we can apply 1.3.1 in plugins {} block.

**Comment by Silthus** [comment]
Mmh I seem to have the same error again in `2.0.0`. Did you maybe rollback this fix with the rollback of `1.3.0`?

**Comment by EntryPointKR** [comment]
No, I didn't rollback this fix. I can't reproduce currently but it caused by Gradle UP-TO-DATE check, please provide your version of Gradle wrapper in your project for further investigation.

**Comment by Silthus** [comment]
I am able to reproduce the bug with a clean clone of this repository: https://github.com/Silthus/sInventoryKeeper/
I clone it, run a gradle import, then removed the `main` class reference from `build.gradle` and started a build.

Then the bug occurs. Does this help you?

**Comment by EntryPointKR** [comment]
Yeah, I can now. Thanks!

**Comment by EntryPointKR** [comment]
It should be fixed by https://github.com/spigradle/spigradle-annotations/commit/314c10f38d82a46183d052e79363af70d2eb6878

**Comment by Silthus** [comment]
Yes that fixed it. Thanks!
